### ISSUE TITLE
v1.17.5 log level setting debug will trigger a crash

### ISSUE THREAD

**Issue by lvelvis** [vmware/kube-fluentd-operator#407]
### Describe the bug

env：
Image version: vmware/kube-fluentd-operator:v1.17.5  
fluent-plugin-detect-exceptions (0.0.14)  

values.yaml
```
logLevel: debug
fluentdLogLevel: debug
```

Question：   When I collect the newly created container, the kfo-log-router container starts to crash and restart, and the following error occurs，These errors will only be triggered when I set the log level to deubg.
```
2023-07-12 17:21:32 +0800 [warn]: fluent/log.rb:381:warn: unexpected error while shutting down on output plugin plugin=Fluent::Kafka2Output plugin_id="object:d0d4" error_class=NoMethodError error="undefined method `synchronize' for nil:NilClass\n\n        @producers_mutex.synchronize {\n                        ^^^^^^^^^^^^"
#<Thread:0x00007ff5e63fa8e8 /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:264 run> terminated with exception (report_on_exception is true):
/usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:596:in `caller_line': undefined method `[]' for nil:NilClass (NoMethodError)

        line = caller(depth+1)[0]
                              ^^^
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:497:in `dump_stacktrace'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:387:in `warn_backtrace'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:287:in `rescue in block (3 levels) in shutdown'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:266:in `block (3 levels) in shutdown'
/usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:256:in `shutdown_producers': undefined method `synchronize' for nil:NilClass (NoMethodError)

        @producers_mutex.synchronize {
                        ^^^^^^^^^^^^
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:248:in `shutdown'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:280:in `block (3 levels) in shutdown'
2023-07-12 17:21:32 +0800 [debug]: fluent/log.rb:339:debug: preparing shutdown output plugin type=:kafka2 plugin_id="object:d1d8"
2023-07-12 17:21:32 +0800 [info]: fluent/log.rb:360:info: shutting down output plugin type=:kafka2 plugin_id="object:d1d8"
2023-07-12 17:21:32 +0800 [debug]: fluent/log.rb:339:debug: preparing shutdown output plugin type=:kafka2 plugin_id="object:d020"
2023-07-12 17:21:32 +0800 [info]: fluent/log.rb:360:info: shutting down output plugin type=:kafka2 plugin_id="object:d020"
2023-07-12 17:21:32 +0800 [error]: fluent/log.rb:402:error: Failed to reload config file: undefined method `[]' for nil:NilClass

        line = caller(depth+1)[0]
                              ^^^
#<Thread:0x00007ff5e63f9df8 /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:264 run> terminated with exception (report_on_exception is true):
2023-07-12 17:21:32 +0800 [warn]: fluent/log.rb:381:warn: unexpected error while shutting down on output plugin plugin=Fluent::Kafka2Output plugin_id="object:d2c8" error_class=NoMethodError error="undefined method `synchronize' for nil:NilClass\n\n        @producers_mutex.synchronize {\n                        ^^^^^^^^^^^^"
/usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:596:in `caller_line': undefined method `[]' for nil:NilClass (NoMethodError)

        line = caller(depth+1)[0]
                              ^^^
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:497:in `dump_stacktrace'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:387:in `warn_backtrace'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:287:in `rescue in block (3 levels) in shutdown'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:266:in `block (3 levels) in shutdown'
2023-07-12 17:21:32 +0800 [warn]: fluent/log.rb:381:warn: unexpected error while shutting down on output plugin plugin=Fluent::Kafka2Output plugin_id="object:d020" error_class=NoMethodError error="undefined method `synchronize' for nil:NilClass\n\n        @producers_mutex.synchronize {\n                        ^^^^^^^^^^^^"
#<Thread:0x00007ff5e63fb590 /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:264 run> terminated with exception (report_on_exception is true):
/usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:596:in `caller_line': undefined method `[]' for nil:NilClass (NoMethodError)

        line = caller(depth+1)[0]
                              ^^^
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:497:in `dump_stacktrace'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:387:in `warn_backtrace'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:287:in `rescue in block (3 levels) in shutdown'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:266:in `block (3 levels) in shutdown'
/usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:256:in `shutdown_producers': undefined method `synchronize' for nil:NilClass (NoMethodError)

        @producers_mutex.synchronize {
                        ^^^^^^^^^^^^
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:248:in `shutdown'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:280:in `block (3 levels) in shutdown'
/usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:256:in `shutdown_producers': undefined method `synchronize' for nil:NilClass (NoMethodError)

        @producers_mutex.synchronize {
                        ^^^^^^^^^^^^
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:248:in `shutdown'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:280:in `block (3 levels) in shutdown'
2023-07-12 17:21:32 +0800 [warn]: fluent/log.rb:381:warn: unexpected error while shutting down on output plugin plugin=Fluent::Kafka2Output plugin_id="object:d1d8" error_class=NoMethodError error="undefined method `synchronize' for nil:NilClass\n\n        @producers_mutex.synchronize {\n                        ^^^^^^^^^^^^"
Unexpected error undefined method `[]' for nil:NilClass

        line = caller(depth+1)[0]
                              ^^^
#<Thread:0x00007ff5e63fa1b8 /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:264 run> terminated with exception (report_on_exception is true):
  /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:596:in `caller_line'
  /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:497:in `dump_stacktrace'
  /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:387:in `warn_backtrace'
  /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:287:in `rescue in block (3 levels) in shutdown'
  /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:266:in `block (3 levels) in shutdown'
/usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:596:in `caller_line': NoMethodError
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:497:in `dump_stacktrace'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/log.rb:387:in `warn_backtrace'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:287:in `rescue in block (3 levels) in shutdown'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:266:in `block (3 levels) in shutdown'
/usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:256:in `shutdown_producers': undefined method `synchronize' for nil:NilClass (NoMethodError)

        @producers_mutex.synchronize {
                        ^^^^^^^^^^^^
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluent-plugin-kafka-0.18.1/lib/fluent/plugin/out_kafka2.rb:248:in `shutdown'
	from /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/fluentd-1.16.1/lib/fluent/root_agent.rb:280:in `block (3 levels) in shutdown'
```

### Reproduction steps

1.
Image version: vmware/kube-fluentd-operator:v1.17.5  
fluent-plugin-detect-exceptions (0.0.14)  
2.
values.yaml
```
logLevel: debug
fluentdLogLevel: debug
```

### Expected behavior

Why do I set the log level to error type, there is no crash

**Comment by slimm609** [comment]
Can you please check this against 1.18?  There were some pretty large changes and refactor for 1.18

**Comment by lvelvis** [comment]
Upgraded to the latest version and it is now working normally, thank you

**Comment by slimm609** [comment]
awesome. thanks for the report
